global:
  scrape_interval: "15s"
  external_labels:
    env: "${FLUENCE_NETWORK}"
    network: "${FLUENCE_NETWORK}"

remote_write:
  - url: "https://mimir.fluence.dev/api/v1/push"
    basic_auth:
      username: test
      password: 1vngmIaFdSHxEEHU

scrape_configs:
  - job_name: "docker-containers"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        filters:
          - name: label
            values:
              - "prometheus_scrape=true"
    relabel_configs:
      - source_labels: [__meta_docker_container_label_prometheus_job]
        target_label: job
      - source_labels: [__meta_docker_container_label_prometheus_instance]
        target_label: instance
      - source_labels: [__address__, __meta_docker_container_label_prometheus_port]
        target_label: __address__
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: ${1}:${2}
