- name: create nox system group
  group:
    name: "{{ nox_group }}"
    system: true
    state: present

- name: create nox system user
  user:
    name: "{{ nox_user }}"
    system: true
    shell: "/sbin/nologin"
    group: "{{ nox_group }}"
    create_home: false
    state: present

- name: create nox directories
  file:
    path: "{{ nox_dir }}/nox-{{ instance }}/state"
    state: directory
    owner: "{{ dir.group | default('nox') }}"
    group: "{{ dir.group | default('nox') }}"
    mode: 0755
  loop: "{{ nox_instances }}"
  loop_control:
    loop_var: instance
    label: "nox-{{ instance }}"

- name: download nox release to localhost
  become: false
  run_once: true
  delegate_to: localhost
  when: nox_run_id | string | length == 0
  block:
    - name: create files directory
      become: false
      run_once: true
      delegate_to: localhost
      file:
        path: "{{ role_path }}/files/{{ nox_version }}"
        state: directory

    - name: download nox binary
      get_url:
        url: "{{ _bin_url }}"
        dest: "{{ role_path }}/files/{{ nox_version }}/{{ _bin }}"
        # checksum: "sha256:{{ _checksums }}"
      register: _download_bin
      until: _download_bin is succeeded
      retries: 5
      delay: 2

    - name: propagate nox binary
      become: true
      run_once: false
      delegate_to: "{{ inventory_hostname }}"
      copy:
        src: "{{ role_path }}/files/{{ nox_version }}/{{ _bin }}"
        dest: "{{ nox_dir }}/nox-{{ instance }}/nox"
        owner: "{{ dir.group | default('nox') }}"
        group: "{{ dir.group | default('nox') }}"
        mode: 0555
      loop: "{{ nox_instances }}"
      loop_control:
        loop_var: instance
        label: "nox-{{ instance }}"
      notify: restart nox
      register: _binary

- name: download nox snapshot to localhost
  become: false
  run_once: true
  delegate_to: localhost
  vars:
    github_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"
  when: nox_run_id | string | length
  block:
    - name: get list of artifacts from GitHub API
      uri:
        url: "https://api.github.com/repos/fluencelabs/nox/actions/runs/{{ nox_run_id }}/artifacts"
        method: GET
        headers:
          Accept: "application/vnd.github.v3+json"
        return_content: true
      register: _artifacts_response

    - name: parse the artifact download URL
      set_fact:
        _artifact_download_url: "{{ item.archive_download_url }}"
      loop: "{{ _artifacts_response.json.artifacts }}"
      when: "item.name == _bin"
      loop_control:
        label: "{{ item.url }}"

    - name: create a temporary directory
      tempfile:
        state: directory
      register: _artifact_temp_dir

    - name: download the artifact
      get_url:
        url: "{{ _artifact_download_url }}"
        dest: "{{ _artifact_temp_dir.path }}/{{ _bin }}.zip"
        headers:
          Authorization: "token {{ github_token }}"
      register: _download_artifact
      until: _download_artifact is succeeded
      retries: 5
      delay: 2

    - name: unarchive the downloaded artifact
      unarchive:
        src: "{{ _artifact_temp_dir.path }}/{{ _bin }}.zip"
        dest: "{{ _artifact_temp_dir.path }}/"

    - name: propagate nox binary
      become: true
      run_once: false
      delegate_to: "{{ inventory_hostname }}"
      copy:
        src: "{{ _artifact_temp_dir.path }}/nox"
        dest: "{{ nox_dir }}/nox-{{ instance }}/nox"
        owner: "{{ dir.group | default('nox') }}"
        group: "{{ dir.group | default('nox') }}"
        mode: 0555
      loop: "{{ nox_instances }}"
      loop_control:
        loop_var: instance
        label: "nox-{{ instance }}"
      notify: restart nox
      register: _binary

  always:
    - name: remove temporary directory
      file:
        path: "{{ _artifact_temp_dir.path }}"
        state: absent
      when: _artifact_temp_dir.path is defined

- name: copy nox config
  tags: config
  template:
    src: "files/{{ nox_project_dir }}/configs/nox-{{ instance }}_Config.toml"
    dest: "{{ nox_dir }}/nox-{{ instance }}/Config.toml"
    owner: "{{ nox_user }}"
    group: "{{ nox_group }}"
    mode: 0640
  loop: "{{ nox_instances }}"
  loop_control:
    loop_var: instance
    label: "nox-{{ instance }}"
  notify: restart nox
  register: _config

- name: create nox unit file
  tags: config
  copy:
    content: "{{ nox_unit_file }}"
    dest: "/etc/systemd/system/nox-@.service"
    owner: root
    group: root
    mode: 0755
  register: _systemd

- name: enable noxes
  systemd:
    name: nox-@{{ instance }}
    enabled: true
    daemon_reload: true
  loop: "{{ nox_instances }}"
  loop_control:
    loop_var: instance
    label: "nox-{{ instance }}"

- name: determine which instances to restart
  vars:
    _binary_changed: "{{ _binary.results | selectattr('changed', 'equalto', true) | map(attribute='instance') | list }}"
    _config_changed: "{{ _config.results | selectattr('changed', 'equalto', true) | map(attribute='instance') | list }}"
    _instances_changed: "{{ (_systemd is changed) | ternary(nox_instances, _binary_changed + _config_changed) }}"
  set_fact:
    _instances_to_restart: "{{ (nox_instances | select('in', _instances_changed) | list) | unique }}"
