- name: download IPFS CLI to localhost
  become: false
  run_once: true
  delegate_to: localhost
  block:
    - name: create IPFS directory on localhost
      file:
        path: "{{ role_path }}/files/ipfs-{{ _ipfs_version }}"
        state: directory

    - name: download IPFS archive
      get_url:
        url: "{{ _ipfs_download_url }}"
        dest: "{{ role_path }}/files/ipfs-{{ _ipfs_version }}/{{ _ipfs_archive }}"
        checksum: "{{ _ipfs_checksums }}"
      register: _download_ipfs
      until: _download_ipfs is succeeded
      retries: 5
      delay: 2

    - name: extract IPFS binary
      unarchive:
        src: "{{ role_path }}/files/ipfs-{{ _ipfs_version }}/{{ _ipfs_archive }}"
        dest: "{{ role_path }}/files/ipfs-{{ _ipfs_version }}"
        extra_opts:
        - "--transform"
        - "s/^kubo/{{ _ipfs_bin }}/"

- name: propagate IPFS binary
  copy:
    src: "{{ role_path }}/files/ipfs-{{ _ipfs_version }}/{{ _ipfs_bin }}"
    dest: "{{ nox_dir }}/ipfs"
    owner: "{{ nox_user }}"
    group: "{{ nox_group }}"
    mode: 0755
