all:
  children:
    servers:
      hosts:
        server-0:
          ansible_host: "<host_ip>"
          ansible_user: "<ssh_user>"
          fluence_instance_id: "nox-0"

      vars:
        # Need to be set according to the required version for the following components.
        nox_version: "0.27.9"
        ipfs_cli_version: "0.26.0"
        ccp_version: "0.13.2"
        # Need to be set according to project name inside files directory
        fluence_project_dir: "<fluence_project_dir>"

        # Select the network, kras = mainnet, dar = testnet
        # fluence_network: "kras" # or "dar"

        # Set only if you want to ship logs/metrics to Cloudless labs
        # fluence_basicauth_username: "<username>"
        # fluence_basicauth_password: "<password>"
        # fluence_promtail_version: "2.9.5"
        # fluence_prometheus_version: "2.52.0"

        # To clean up the state, uncomment these
        # Don't forget to comment afterwards
        # nox_cleanup_state: true
        # ccp_cleanup_state: true
