all:
  children:
    servers:
      hosts:
        server-0:
          ansible_host: "<host_ip>"
          ansible_user: "<ssh_user>"
          fluence_instance_id: "nox-0"

      vars:
        # Need to be set according to the required version for the following components.
        nox_version: "0.24.0"
        ipfs_cli_version: "0.26.0"
        ccp_version: "0.11.0"
        # Need to be set according to project name inside files directory
        fluence_project_dir: "<fluence_project_dir>"
        # Set only if you want to ship logs/metrics to Cloudless labs
        # fluence_basicauth_username: "<username>"
        # fluence_basicauth_password: "<password>"
        # fluence_promtail_version: "2.9.5"
        # fluence_prometheus_version: "2.52.0"
        # fluence_network: "kras" # or "dar"
        vm_name: sandbox
        vm_image_s3_bucket: your-s3-bucket-name
        vm_image_s3_key: path/to/your/vm-image.qcow2
        vm_image_local_path: /var/lib/libvirt/images/{{ vm_name }}.qcow2
        bridge_name: br422442
        vm_mac: "{{ '52:54:00' | community.general.random_mac(seed=inventory_hostname) }}"
        vm_uuid: "{{ '123' | to_uuid }}"
        physical_iface: "dummy0"  # Physical network interface to be added to the bridge
        vm_ram: 1048576  # RAM size in KiB (1 GiB)
